apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

images:
  - name: ghcr.io/pablo-moreno/wallets/wallets
    newTag: latest

secretGenerator:
  - name: wallets-secrets
    envs:
      - ".env"
    options:
      annotations:
        argocd.argoproj.io/hook: "PreSync"
        argocd.argoproj.io/sync-wave: "1"
