apiVersion: v1
kind: Service
metadata:
  name: wallets
spec:
  selector:
    app: wallets
  ports:
  - port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
